spring:
  datasource:
    url: jdbc:mysql://localhost/singers?serverTimezone=GMT%2B8
    username: root
    password: dy123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true